POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
     "author": "Test author",
    "title": "On let vs const",
    "url": "https://overreacted.io/let-vs-const/",
    "likes": 10
    
}
###
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": 3
}
###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "name": "Muskan",
    "username": "muskan123"
}
###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "name": "Raju",
    "username": "raju@example.com"
}
###
PUT http://localhost:3001/api/users/muskan123
Content-Type: application/json

{
    "newUsername": "muskan_new",
    "name": "Muskan Sharma"
}
###
GET http://localhost:3001/api/users/
###



