POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11c2thbkBleGFtcGxlLmNvbSIsImlkIjoyLCJpYXQiOjE3NTU3OTA5NTF9.rGwxVLMVbpQsdKx2jPNg7N5QHJ2mBfQZCTSR_UEdWx8

{
  "title": "Hey blog",
  "author": "Muskan",
  "url": "http://example.com",
  "likes": 0,
  "year": 2012
}
###
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": 3
}
###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "name": "Muskan",
    "username": "muskan@example.com"
}
###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "name": "Raju",
    "username": "raju@example.com"
}
###
PUT http://localhost:3001/api/users/muskan123
Content-Type: application/json

{
    "newUsername": "muskan_new",
    "name": "Muskan Sharma"
}
###
GET http://localhost:3001/api/users/
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "muskan@example.com",
    "password": "secret"
}
###
DELETE http://localhost:3001/api/blogs/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhanVAZXhhbXBsZS5jb20iLCJpZCI6MywiaWF0IjoxNzU1NjIwMzkzfQ.-C6m1htya47702snVv1yrDL2FYLEIYlMhQ3Bbv_VQ88


