POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "My first blog",
  "author": "Alice",
  "url": "https://example.com",
  "likes": 5
}
###
GET http://localhost:3003/api/blogs