
DELETE http://localhost:3003/api/blogs/68451960a6e395e221fa2b0c
###
DELETE http://localhost:3003/api/blogs/68451960a6e395e221fa2b0e
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "password123"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Clean Slate Blog",
  "author": "mluukkai",
  "url": "http://example.com/blog1",
  "likes": 7
}
###
GET http://localhost:3003/api/blogs
###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "mluukkai",
    "password": "password123"
}